name: Build Image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@v1.0.3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: 'bidmcdigitalpsychiatry/lamp-college-study'
          auto_tag: true
