name: Build College V3 image
on:
  push:
    branches: 
      - college_v3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jerray/publish-docker-action@v1.0.3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        repository: 'bidmcdigitalpsychiatry/lamp-college-study-v3'
        auto_tag: true
